## Server Properties
server:
  port: 8081

spring:
  config:
    import: vault://secret/app/pres/demo
    activate:
      on-profile: "demo"
  datasource:
    username: ${pres.db.username}
    password: ${pres.db.password}
    url: ${pres.db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


